### ISSUE TITLE
Capability to find a users Posts

### ISSUE THREAD

**Issue by EstebanBorai** [whizzes/playa#98]
Extend current `posts` query to allow users to fetch a specific user posts.

https://github.com/whizzes/gabble/blob/main/crates/server/src/graphql/modules/post/query/posts.rs#L13-L44

**Comment by CudiLala** [comment]
Hello!
So I can add a filter just like that of fetching users by email?

**Comment by EstebanBorai** [comment]
> Hello!
> So I can add a filter just like that of fetching users by email?

Sure thing!
